### ISSUE TITLE
Backfill India 7 Day ECMWF Archive

### ISSUE THREAD

**Issue by devsjc** [openclimatefix/dagster-dags#103]
Create an Archive of 7-day horizon ECMWF data for India. Follows on from the coding work done in https://github.com/openclimatefix/nwp-consumer/issues/138.

**Comment by devsjc** [comment]
## 2024-04-24

Currently all of 2022 is downloaded. 2023 is in progress.

**Comment by devsjc** [comment]
This has completed downloading 2022-2024. Do we want to go back further?

**Comment by peterdudfield** [comment]
I think this is good for the moment, ill close if thats ok?
