### ISSUE TITLE
NWP dagster Planetary

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/dagster-dags#51]
Following on from [here](https://github.com/openclimatefix/dagster-dags/issues/50) to get NWP using dagster using planetary computing

Some docs for how to use plantary computing are here
https://planetarycomputer.microsoft.com/docs/overview/about

Useful code
`kbatch job submit --image=ghcr.io/openclimatefix/nwp-consumer --args='["check"]' --name=nwp-consumer --output=name` 
This returns an `job-name`.Then to get the logs do
`kbatch pod list --job-name=nwp-consumer-9rfzs --output=name`
`kbatch pod logs nwp-consumer-9rfzs-pbdzt --stream`

- [x] Sign up to planetary computers
- [ ] First get ICON working on planetary
- [ ] Test NWP consumer pushes to Hugging Face uese kbatch, might need to play with memory
- [ ] Put kbatch into Dagster
- [ ] Set Dagster to track Hugging Face

`kbatch job submit --image=ghcr.io/openclimatefix/nwp-consumer --args='["consume", "--source", "icon", "--name", "nwp-consumer", "sink=huggingface"]'--envs="{\"HUGGINGFACE_TOKEN\":xxx,\"HUGGINGFACE_REPO_ID\":openclimatefix/dwd-icon-eu, \"ICON_PARAMETER_GROUP\":\"full\"}"  --name=nwp-consumer --output=name`

**Comment by peterdudfield** [comment]
FYI: @devsjc @jacobbieker

**Comment by devsjc** [comment]
Began work on this on new branch `feature/planetary-computer`.

**Comment by devsjc** [comment]
Requires some modifications to the huggingface implementation in the consumer. See https://github.com/openclimatefix/nwp-consumer/issues/91.

**Comment by peterdudfield** [comment]
Well done @devsjc, will in then just need updating where it saving too?

**Comment by devsjc** [comment]
So we did in fact hit the commit limit saving raw files. Fix tracked by the following issue: https://github.com/openclimatefix/nwp-consumer/issues/106

**Comment by devsjc** [comment]
Once again deployed and just going to test it for a little bit against a test dataset until we're happy with it.

**Comment by peterdudfield** [comment]
What you thinking about how long your leave it running before switching? 
1 hour / 1 day / 1 week?

**Comment by devsjc** [comment]
ICON has runs every 6 hours, I think once I've seen two of those go through (one manual backfill, one scheduled backfill) and I've got Jacob to check he's happy with the Zarr file in huggingface, I'll be happy to move it over. So I can set off the first backfill once #67 is closed, and a scheduled one will go off at 12:00. Assuming it will take a few hours to run, might just be able to be happy with it before the end of the day!

**Comment by devsjc** [comment]
First backfill attempt for europe, 2024-02-08T12:00 set off [here](http://localhost:3003/runs/de6edd63-b454-453f-9520-7c39c85f1b16)

**Comment by devsjc** [comment]
The above failed due to ReadTimeout errors listing pods. See #69 for tracking.

**Comment by devsjc** [comment]
Backfill tests:
 - [europe, 2024-02-09T00:00](http://localhost:3003/runs/40a93dbf-d7a1-440c-bb46-417a0b0ed650)
 - [global, 2024-02-09T00:00](http://localhost:3003/runs/a5997752-03a7-4ea8-bd07-538ec1f45234)

**Comment by devsjc** [comment]
These backfill tests failed - kubernetes killed the containers as they used too much memory. There's two possibilities here:

1. The storing of the raw files used up all the available memory (they are larger than the resultant zarr)
2. The merging of the final zarr used up all the available memory

If it is the first case, this could be solevable by distributing the workload across multiple pods using planetary computer's dask cluster features. Each pod would have to handle fewer individual files and so store less memory. This would also speed the process up as it would parallelise the compute.
If it is the second case, this would not help as the final merge would use up all the available memory of the single pod that would run on as before.

As such we are going to hope it the first issue and implement distributing via a dask gateway into the nwp-consumer. See https://github.com/openclimatefix/nwp-consumer/issues/110

**Comment by jacobbieker** [comment]
If https://github.com/openclimatefix/nwp-consumer/issues/110 doesn't fix it, we probably could switch to uploading the zarrs as separate ones to HF? As long as they are separated in a reasonable fashion (ideally, all surface, then all pressure levels, or something like that) it would be slightly annoying to use, but workable, incase 2. is the issue.

**Comment by devsjc** [comment]
I've thought of one more thing to try beforehand - I've put in a small change just to request more resources from the cluster to see if that helps.

**Comment by devsjc** [comment]
Fixed the memory error, the next issue however is 
```
cannot reindex or align along dimension 'step' because of conflicting dimension sizes: {1, 92} (note: an index is found along that dimension with size=92)
```
Occurring at [this point](https://github.com/openclimatefix/nwp-consumer/blob/8a36666c1841739d5d9d1a222e7169bd40a44776/src/nwp_consumer/internal/service/service.py#L441) - odd because that very function should be padding with zeros to make the shapes match. Discussing with Jacob.

**Comment by devsjc** [comment]
Now dealing with the icon client of the consumer failing to find downloaded files, for instance:

```
{ "error": "[Errno 2] No such file or directory: '/tmp/nwpc/icon_global_icosahedral_single-level_2024021900_006_ALB_RAD.grib2'", "filename": "/venv/lib/python3.12/site-packages/nwp_consumer/internal/inputs/icon/client.py", "line": "", "lineno": 331 }
```

**Comment by devsjc** [comment]
The above has lead to the implementation of the following changes in the consumer and dagster:
- https://github.com/openclimatefix/nwp-consumer/issues/121
- https://github.com/openclimatefix/dagster-dags/commit/dc5fc9664fd75e58c4ff3dd8adcdf80c6d6061a0

**Comment by devsjc** [comment]
Splitting out the process to handle single-level and multi-level files seperately has detailed a firther problem in the design of the consumer. In short, dask wasn't parallelising tasks as effectively as it could be, which may have been leading to calls to `xr.Merge` that were difficult to perform. See https://github.com/openclimatefix/nwp-consumer/issues/135 for details of the change.

Effectively this will split up the `xr.Merge` process from attempting to merge all icon files together in one call, to an initial merge of only the files in each dask partition, followed by a merging of the merged partitions. This (hopefully) should mean the datasets look more similar at all points in the merge process.

**Comment by devsjc** [comment]
Closing this as Planetary are discontinuing the ability to run batch jobs.
