### ISSUE TITLE
Satellite Planetary Dagster

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/dagster-dags#52]
Following on from https://github.com/openclimatefix/dagster-dags/issues/51

- [x] Sign up to planetary computers, using openclimatefix email
- [x] Sign up to EUMETSAT, using openclimatefix email
- [ ] Get python file to get satellite files (link - https://github.com/jacobbieker/planetary-datasets/blob/main/planetary_datasets/conversion/zarr/eumetsat.py)
- [x] Test Satellite Consumer pushes to Hugging Face using kbatch, (done)
- [ ] Set kbatch in Dagster
- [ ] Set Dagster to track Hugging Face

**Comment by peterdudfield** [comment]
FYI: @devsjc @jacobbieker

**Comment by jacobbieker** [comment]
They've now closed this, so not relevant.
