### ISSUE TITLE
Meteomatics India Archive

### ISSUE THREAD

**Issue by devsjc** [openclimatefix/dagster-dags#98]
For the 7 day forecast for RUVNL some meteomatics data is required. The exact area/sites, steps, and parameters are to be determined.

[Part of RUVNL]

**Comment by devsjc** [comment]
Is this already covered by the data at `/mnt/storage_b/nwp/meteomatics/nw_india/solar_archive` and `/mnt/storage_b/nwp/meteomatics/nw_india/wind_archive`?

**Comment by peterdudfield** [comment]
Ill close this for the moment
