### ISSUE TITLE
ECMWF Whole India Archive

### ISSUE THREAD

**Issue by devsjc** [openclimatefix/dagster-dags#99]
For Adani an ECMWF archive of data from north india is required. This will match the steps/parameters/horizon of the northwest india archive, but differ in area. The exact grid bounds are to be determined.

**Comment by devsjc** [comment]
@jacobbieker is there a specific lat/long area bound you know we might want for this archive?

**Comment by jacobbieker** [comment]
Not sure with the extended one, I would go with like 4 or 5 degrees further in every direction from the bounding box around the sites, if that makes sense?

**Comment by devsjc** [comment]
After conversation with @peterdudfield and Dan, we have decided to make this archive a 55hr horizon archive of the entirety of India. India's bounding box is 68w, 7s, 97e, 35n, so with a buffer of 100km this becomes 67w, 97e, 6s, 35n.

**Comment by devsjc** [comment]
This requires two tasks:
- [ ] Update the ECMWF module of the consumer for india with the newly defined area: see [this pr](https://github.com/openclimatefix/nwp-consumer/pull/149)
- [ ] Add a new asset collection to dagster for the archive and bump the consumer version

**Comment by devsjc** [comment]
Created test week-long backfill for first week of 2024 at http://localhost:3003/overview/backfills/kqtarwyx
